---
title: 'Homework 02: Conceptual Exercises'
author: Ellen Hsieh
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1.
a.
```{r}
set.seed(524)

bs = c()
for (i in 1:1000){
  b0 = 30
  b1 = 55
  X = rnorm(1000, 0, 1)
  e = rnorm(1000, 0, 0.25)
  Y = b0 + b1 * X + e
  fit = lm(Y ~ X)
  b1_hat = coef(fit)[2]
  bs = c(bs, b1_hat)
}
bias = b1 - mean(bs)
bias
```

The bias is so small, so it's an unbiased estimator.

b.
```{r}
sigma2 = seq(0.25, 10, 0.25)
ss = c()
for (s in sigma2){
  var_b1 = c()
  for (i in 1:1000){
    Y = b0 + b1*X + rnorm(1000, 0, s)
    fit = lm(Y ~ X)
    var_b1_temp = summary(fit)$coef[2, 2]^2
    var_b1 = c(var_b1, var_b1_temp)
  }
  ss = c(ss, mean(var_b1))
}
plot(sigma2, ss, xlab = expression(sigma^2),ylab = expression(paste("variance of ", hat(beta[1]), "")), type = "l")
```

### 2.
a.
```{r}
library(MASS)

sim = function(N){
  result = data.frame()
  for (r in seq(-0.9, 0.9, 0.1)){
    se_b1 = c()
    se_b3 = c()
    for (i in 1:1000){
      m = matrix(c(1, r, 0, r, 1, 0, 0, 0, 1), 3, 3)
      Y = mvrnorm(N, c(0, 0, 0), m)
      data = data.frame(cbind(Y, rnorm(N)))
      colnames(data) = c("X1", "X2", "X3", "e")
      data$Y = data$X1 + data$X2 + data$X3 + data$e
      fit = lm(Y ~ X1 + X2 + X3, data)
      se_b1_temp = summary(fit)$coef[2, 2]
      se_b3_temp = summary(fit)$coef[4, 2]
      se_b1 = c(se_b1, se_b1_temp)
      se_b3 = c(se_b3, se_b3_temp)
    }
  result = rbind(result, c(r, mean(se_b1), mean(se_b3)))
  colnames(result) = c("r", "se_b1", "se_b3")
  }
  return(result)
}
result = sim(100)
plot(result$r, result$se_b1, type = "l", xlab = "r", ylab = expression(se(hat(beta[1]))))
```

b.
```{r}
plot(result$r, result$se_b3, type = "l", xlab = "r", ylab = expression(se(hat(beta[3]))))
```

c.
```{r}
result2 = sim(300)
result3 = sim(1000)

plot(result$r, result$se_b1, xlab = "r", ylab = expression(se(hat(beta[1]))), col = 1, type = "l", ylim = c(0, .6))
lines(result2$r, result2$se_b1, col = 2)
lines(result3$r, result3$se_b1, col = 3)
legend("topright", c("N = 100", "N = 300", "N = 1000"), col = c(1, 2, 3), lty = 1)
```

```{r}
plot(result$r, result$se_b3, xlab = "r", ylab = expression(se(hat(beta[3]))), col = 1, type = "l", ylim = c(0, .6))
lines(result2$r, result2$se_b3, col = 2)
lines(result3$r, result3$se_b3, col = 3)
legend("topright", c("N = 100", "N = 300", "N = 1000"), col = c(1, 2, 3), lty = 1)
```

